[package]
name = "faster_freezed"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
pathdiff = "0.2.3"
streaming-iterator = "0.1.9"
tree-sitter = "0.24.7"
tree-sitter-dart = "0.0.4"
